### ISSUE TITLE
Bad Enumerable implementation for Cursors

### ISSUE THREAD

**Issue by Virviil** [elixir-mongo/mongodb#110]
i can `Enum.to_list` and `Enum.count` properly on cursor, but calling `Enum.at` or `Enum.take` causes to such an error:

```bash
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
                    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:925: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:741: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1132: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
          (mongodb) lib/mongo.ex:386: Mongo.kill_cursors/3
           (elixir) lib/stream.ex:1250: Stream.do_resource/5
           (elixir) lib/enum.ex:758: Enum.fetch_enumerable/3
```

**Comment by ericmj** [comment]
It's impossible to say what's wrong when you don't show your code but I would guess you are missing the `:pool` option.

**Comment by Virviil** [comment]
```elixir
 @spec select(true | false) :: %Mongo.Cursor{} 
 def select(following) do
   Mongo.find(
     :mongo,
     "following", 
     %{
       following: following
     }, 
     pool: DBConnection.Poolboy
   ) 
 end 
```

and then

```bash
iex(2)> Following.select(false) |> Enum.count
75000
iex(3)> Following.select(false) |> Enum.at(0) 
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
                    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:925: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:741: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1132: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
          (mongodb) lib/mongo.ex:386: Mongo.kill_cursors/3
           (elixir) lib/stream.ex:1250: Stream.do_resource/5
           (elixir) lib/enum.ex:758: Enum.fetch_enumerable/3
```

in supervisor:
```elixir
worker(Mongo, [[name: :mongo, database: "marketing", pool: DBConnection.Poolboy]]),
```

**Comment by ericmj** [comment]
Do you have the same issue on master? I think it has been fixed but not released.

**Comment by kexoth** [comment]
I have the same issue. This happens for me if I'm using a `:pool` and any other option e.g. `:limit`, `:batch`.

**Comment by ericmj** [comment]
Do you have same issue on master?

**Comment by ankhers** [comment]
I'm going to close this for lack of activity. Feel free to open if you are still having issues on the latest release.

**Comment by BogdanHabic** [comment]
Hey, I'm still having the issue even after updating to 0.3.0.

I also tried master and it also has the issue.

I'm here to provide any information you need.

**Comment by ankhers** [comment]
@BogdanHabic Can you please provide some code? I can't seem to replicate the issue.

My (simple) test works.

```elixir
iex(1)> {:ok, conn} = Mongo.start_link(database: "test")
iex(2)> cursor = Mongo.find(conn, "collection", %{name: "name"}, limit: 2)
iex(3)> cursor |> Enum.at(0) |> IO.inspect()
```

**Comment by BogdanHabic** [comment]
Hey @ankhers,
Sure, here is the code that fails:

```
iex(1)> Mongo.start_link(database: "test", port: 27017, name: :test, pool: DBConnection.Poolboy)
{:ok, #PID<0.175.0>}
iex(2)> Mongo.find(:test, "testcol", %{}) |> Enum.to_list
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
                    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
          (mongodb) lib/mongo.ex:408: Mongo.raw_find/5
          (mongodb) lib/mongo/cursor.ex:40: anonymous fn/6 in Enumerable.Mongo.Cursor.start_fun/6
           (elixir) lib/stream.ex:1240: anonymous fn/5 in Stream.resource/3
```

**Comment by ankhers** [comment]
Alright, I think I was able to replicate the issue.

```elixir
iex(1)> {:ok, conn} = Mongo.start_link(database: "test", pool: DBConnection.Poolboy)
iex(2)> cursor = Mongo.find(conn, "collection", %{name: "name"})
iex(3)> cursor |> Enum.at(0) |> IO.inspect()
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
                    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:925: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:741: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1132: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
          (mongodb) lib/mongo.ex:408: Mongo.raw_find/5
          (mongodb) lib/mongo/cursor.ex:40: anonymous fn/6 in Enumerable.Mongo.Cursor.start_fun/6
           (elixir) lib/stream.ex:1240: anonymous fn/5 in Stream.resource/3
```

However, if I include the `:pool` option for the query itself

``` elixir
iex(1)> {:ok, conn} = Mongo.start_link(database: "test", pool: DBConnection.Poolboy)
iex(2)> cursor = Mongo.find(conn, "collection", %{name: "name"}, pool: DBConnection.Poolboy)
iex(3)> cursor |> Enum.at(0) |> IO.inspect()
```

It works as expected. There is also a note on [`Mongo.start_link/1`](https://github.com/ericmj/mongodb/blob/master/lib/mongo.ex#L83-L85) stating that you need to pass the `:pool` option every time if you are not using the default.

Can you let me know if this solves your problem?

**Comment by BogdanHabic** [comment]
This does solve the issue, but I'm wondering now, why is the extra `:pool` parameter needed if it's already provided in the `Mongo.start_link/1` function?

**Comment by ankhers** [comment]
It is because of the way the [dbconnection](https://github.com/elixir-ecto/db_connection/) package works, specifically when attempting to [checkout](https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection.ex#L919) a connection from the pool. It looks in the options provided by the function calls and uses `DBConnection.Connection` if it does not find one.

**Comment by ericmj** [comment]
One workaround is to wrap the the `Mongo` module with functions that always pass the `:pool` option. Similar to how the old `Mongo.Pool` worked.
